version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: web1
      POSTGRES_USER: web1user
      POSTGRES_PASSWORD: web1pass
    ports:
      - "5432:5432"